export enum ActionTypeKeys {
    FETCH_TODOS = "FETCH_TODOS",
    FETCH_TODOS_SUCCESS = "FETCH_TODOS_SUCCESS",
    FETCH_TODOS_FAIL = "FETCH_TODOS_FAIL",
    ADD_TODO = "ADD_TODO",
    ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS",
    ADD_TODO_FAIL = "ADD_TODO_FAIL"
}